Pom 297 pom 270
coi-gov-pl/gui-web-pomogamukrainie-forum pull request #119
Opened 2022-03-20 16:44 UTC by oleksandrdevqube

POM- 297 Dodanie paginacji po pierwszym zapytaniu
POM- 270 Dodanie routing params zeby mozna bylo zapisywac stan strony i wyszukiwarki

2022-03-20 17:40 UTC, neu5 approved these changes

2022-03-20 17:52 UTC, bbartosiak commented
zbudowałem lokalnie:
Nie wyświetla inicjalnych parametrów w query: ogloszenia/api/accommodations

2022-03-20 18:00 UTC, mgol requested changes
Some important remarks to solve before merging to not cause regressions.

2022-03-20 18:00 UTC, mgol commented on src/app/shared/components/paginator/paginator.component.ts
> +    localStorage.setItem('size', JSON.stringify(event.pageSize));
`size` is a very generic term and `localStorage` is global per domain. Quite often, lots of third party libraries are loaded which can also use `localStorage`. I think we should prefix all the fields, e.g. `pomagamukrainie-size`?

2022-03-21 08:47 UTC, broslukasz commented on src/app/shared/components/paginator/paginator.component.ts
> +    this.params$ = this.route.queryParams;
Please move it to move on init. Keeping logic in constructor always cause problem.

2022-03-22 08:42 UTC, bbartosiak commented on src/app/core/store-url/store-url.service.ts
> +          localStorage.setItem('pomagamukrainie-query', events[0].urlAfterRedirects.split('?')[1]);
do poprawy w następnej PR:
pomagamukrainie-url
pomagamukrainie-query

to możesz dać do enum'a, aby nie zrobić przypadkiem literówki

2022-03-22 08:42 UTC, bbartosiak commented on src/app/find-help/accommodation-search/accommodation-search-form/accommodation-search-form.component.ts
> +import { StoreUrlService } from '@app/core/store-url/store-url.service';
@app/core/store-url

2022-03-22 08:42 UTC, bbartosiak commented on src/app/find-help/material-aid-search/material-aid-search-form/material-aid-search-form.component.ts
> +import { StoreUrlService } from '@app/core/store-url/store-url.service';
@app/core/store-url

2022-03-22 08:42 UTC, bbartosiak commented on src/app/find-help/transport-search/transport-search-form/transport-search-form.component.ts
> +import { StoreUrlService } from '@app/core/store-url/store-url.service';
@app/core/store-url

2022-03-22 08:43 UTC, bbartosiak commented on src/app/find-help/view-offer-accommodation/view-offer-accommodation.component.ts
> +import { StoreUrlService } from '@app/core/store-url/store-url.service';
@app/core/store-url

2022-03-22 08:43 UTC, bbartosiak commented on src/app/my-account/my-account.module.ts
> +import { PaginatorModule } from '@app/shared/components/paginator/paginator.module';
@app/shared/components

2022-03-22 08:43 UTC, bbartosiak commented on src/app/my-account/my-account.module.ts
> +import { PaginatorModule } from '@app/shared/components/paginator/paginator.module';
@app/shared/components

2022-03-22 08:43 UTC, bbartosiak commented on src/app/shared/components/paginator/paginator.component.ts
> +    localStorage.setItem('pomagamukrainie-size', JSON.stringify(event.pageSize));
tpomagamukrainie-size -> o powinno byc w enum: z pozostałymi kluczami

2022-03-22 08:50 UTC, merged