Fix mobile nav toggling
coi-gov-pl/gui-web-pomogamukrainie-forum pull request #250
Opened 2022-03-28 14:39 UTC by neu5

2022-03-28 14:44 UTC, mgol requested changes

2022-03-28 14:44 UTC, mgol commented on src/app/core/site-header/site-header.component.ts
> +    const self = this;
Use arrow functions and don't assign `this` to anything.

2022-03-28 14:48 UTC, mgol approved these changes, later dismissed

2022-03-28 15:12 UTC, bbartosiak commented on src/app/core/site-header/site-header.component.ts
> +    this.navBar.nativeElement.addEventListener('hidden.bs.collapse', () => {
należy się odpinać od eventListenerów.
Mozna to zrobić na dwa sposoby
1. Użycie Renderer2
const functionToRemoveEventListener = this.render.listen(<element>, 'shown.bs.collapse', () => {});
w ngOnDestroy -> functionToRemoveEventListener();

2. fromEvent z rxjs fromEvent(this.navBar.nativeElement, shown.bs.collapse).subscribe()
a) użyc .pipe(takeUntil(this.eventSub$))

2022-03-29 11:17 UTC, broslukasz approved these changes, later dismissed

2022-04-01 20:35 UTC, mgol approved these changes

2022-04-01 20:35 UTC, merged