[refactoring] Extract description and phone number form controls to separate components
coi-gov-pl/gui-web-pomogamukrainie-forum pull request #252
Opened 2022-03-28 20:27 UTC by felix1313

Extracting the phone number caused a small visual change due to bootstrap grid limitations (It's not possible to keep 2:3 ratio as there must be 12 columns). But I hope it's not a big deal.

![Screenshot from 2022-03-28 22-26-33](https://user-images.githubusercontent.com/9641160/160481259-9915c278-af9a-4d81-8131-95829a05f6b6.png)

2022-04-01 20:36 UTC, mgol reviewed
Should this be targeted at `develop`, not `main`? If so, please change the base branch of the PR.

2022-04-13 07:24 UTC, klimtron requested changes

2022-04-13 07:24 UTC, klimtron commented on src/app/give-help/give-help-form/offer-phone-number-input/offer-phone-number-input.component.ts
> +  emitPhoneNumber() {
Błędna logika mergowania i wysyłania telefonu odbiegająca od tego co mamy teraz.

2022-04-13 18:43 UTC, felix1313 commented
Too many conflicts with current version.

2022-04-13 18:43 UTC, closed without merging